test_0 (__main__.lab4a.test_0)
[Lab 4] - [Investigation 1] - [Part 2] - Data Structures - Test for file creation: ./lab4a.py ... ok
test_a (__main__.lab4a.test_a)
[Lab 4] - [Investigation 1] - [Part 2] - Data Structures - Test for errors running: ./lab4a.py ... ok
test_a1 (__main__.lab4a.test_a1)
[Lab 4] - [Investigation 1] - [Part 2] - Data Structures - Test for correct shebang line: ./lab4a.py ... ok
test_a_function_join (__main__.lab4a.test_a_function_join)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_sets() fails without 2 arguments ... ok
test_b_function_join (__main__.lab4a.test_b_function_join)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_sets() fails without 2 arguments ... ok
test_c_function_join (__main__.lab4a.test_c_function_join)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_sets() fails without 2 arguments ... ok
test_d_function_join_sets (__main__.lab4a.test_d_function_join_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_sets() joins sets together {1,2,3,4,5} and {2,1,0,-1,-2} ... ERROR
test_e_function_join_sets (__main__.lab4a.test_e_function_join_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_sets() joins sets together ... ERROR
test_f_function_match_sets (__main__.lab4a.test_f_function_match_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_sets() ... ERROR
test_g_function_match_sets (__main__.lab4a.test_g_function_match_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_sets() ... ERROR
test_h_function_diff_sets (__main__.lab4a.test_h_function_diff_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_sets() ... ERROR
test_i_function_diff_sets (__main__.lab4a.test_i_function_diff_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_sets() ... ERROR
test_0 (__main__.lab4b.test_0)
[Lab 4] - [Investigation 1] - [Part 2] - Data Structures - Test for file creation: ./lab4b.py ... ok
test_a (__main__.lab4b.test_a)
[Lab 4] - [Investigation 1] - [Part 2] - Data Structures - Test for errors running: ./lab4b.py ... ok
test_a1 (__main__.lab4b.test_a1)
[Lab 4] - [Investigation 1] - [Part 2] - Data Structures - Test for correct shebang line: ./lab4b.py ... ok
test_a_function_join (__main__.lab4b.test_a_function_join)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_lists() fails without 2 arguments ... ok
test_b_function_join (__main__.lab4b.test_b_function_join)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_lists() fails without 2 arguments ... ok
test_c_function_join (__main__.lab4b.test_c_function_join)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_lists() fails without 2 arguments ... ok
test_d_function_join_lists (__main__.lab4b.test_d_function_join_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_lists() joins lists together {1,2,3,4,5} and {2,1,0,-1,-2} ... ERROR
test_e_function_join_lists (__main__.lab4b.test_e_function_join_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_lists() joins lists together ... ERROR
test_f_function_match_lists (__main__.lab4b.test_f_function_match_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_lists() ... ERROR
test_g_function_match_lists (__main__.lab4b.test_g_function_match_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_lists() ... ERROR
test_h_function_diff_lists (__main__.lab4b.test_h_function_diff_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_lists() ... ERROR
test_i_function_diff_lists (__main__.lab4b.test_i_function_diff_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_lists() ... ERROR
test_0 (__main__.lab4c.test_0)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - Test for file creation: ./lab4c.py ... ok
test_a (__main__.lab4c.test_a)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - Test for errors running: ./lab4c.py ... ok
test_a1 (__main__.lab4c.test_a1)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - Test for correct shebang line: ./lab4c.py ... ok
test_b_function_create_dictionary (__main__.lab4c.test_b_function_create_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function create_dictionary() fails without 2 arguments ... ok
test_d_function_shared_values (__main__.lab4c.test_d_function_shared_values)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function shared_values() fails without 2 arguments ... ok
test_e_function_create_dictionary (__main__.lab4c.test_e_function_create_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function create_dictionary() ... ERROR
test_f_function_create_dictionary (__main__.lab4c.test_f_function_create_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function create_dictionary() ... ERROR
test_i_function_split_dictionary (__main__.lab4c.test_i_function_split_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function shared_values() ... ERROR
test_j_function_split_dictionary (__main__.lab4c.test_j_function_split_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function shared_values() ... ERROR
test_0 (__main__.lab4d.test_0)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - Test for file creation: ./lab4d.py ... ok
test_a (__main__.lab4d.test_a)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - Test for errors running: ./lab4d.py ... ok
test_a1 (__main__.lab4d.test_a1)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - Test for correct shebang line: ./lab4d.py ... ok
test_b_function_first_five (__main__.lab4d.test_b_function_first_five)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function first_five() ... ok
test_c_function_first_five (__main__.lab4d.test_c_function_first_five)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function first_five() ... ok
test_d_function_last_seven (__main__.lab4d.test_d_function_last_seven)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function last_seven() ... ok
test_e_function_last_seven (__main__.lab4d.test_e_function_last_seven)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function last_seven() ... ok
test_f_function_middle_number (__main__.lab4d.test_f_function_middle_number)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function middle_number() ... ok
test_g_function_middle_number (__main__.lab4d.test_g_function_middle_number)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function middle_number() ... ok
test_h_function_first_three_last_three (__main__.lab4d.test_h_function_first_three_last_three)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function first_three_last_three() ... ok
test_i_function_first_three_last_three (__main__.lab4d.test_i_function_first_three_last_three)
[Lab 4] - [Investigation 2] - [Part 1] - Strings - function first_three_last_three() ... ok
test_0 (__main__.lab4e.test_0)
[Lab 4] - [Investigation 2] - [Part 2] - Strings - Test for file creation: ./lab4e.py ... ok
test_a (__main__.lab4e.test_a)
[Lab 4] - [Investigation 2] - [Part 2] - Strings - Test for errors running: ./lab4e.py ... ok
test_a1 (__main__.lab4e.test_a1)
[Lab 4] - [Investigation 2] - [Part 2] - Strings - Test for correct shebang line: ./lab4e.py ... ok
test_b_function_is_digits (__main__.lab4e.test_b_function_is_digits)
[Lab 4] - [Investigation 2] - [Part 2] - Functions - is_digits("3058") has correct output ... ok
test_c_function_is_digits (__main__.lab4e.test_c_function_is_digits)
[Lab 4] - [Investigation 2] - [Part 2] - Functions - is_digits("x3058") has correct output ... ok
test_d_function_is_digits (__main__.lab4e.test_d_function_is_digits)
[Lab 4] - [Investigation 2] - [Part 2] - Functions - is_digits("8503x") has correct output ... ok
test_e_function_is_digits (__main__.lab4e.test_e_function_is_digits)
[Lab 4] - [Investigation 2] - [Part 2] - Functions - is_digits("8503") has correct output ... ok

======================================================================
ERROR: test_d_function_join_sets (__main__.lab4a.test_d_function_join_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_sets() joins sets together {1,2,3,4,5} and {2,1,0,-1,-2}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 88, in test_d_function_join_sets
    self.assertTrue(lab4aStudent.join_sets(set1,set2) == set1|set2, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4a' has no attribute 'join_sets'

======================================================================
ERROR: test_e_function_join_sets (__main__.lab4a.test_e_function_join_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_sets() joins sets together
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 100, in test_e_function_join_sets
    self.assertTrue(lab4aStudent.join_sets(set1,set2) == set1|set2, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4a' has no attribute 'join_sets'

======================================================================
ERROR: test_f_function_match_sets (__main__.lab4a.test_f_function_match_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_sets()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 112, in test_f_function_match_sets
    self.assertTrue(lab4aStudent.match_sets(set1,set2) == set1&set2, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4a' has no attribute 'match_sets'

======================================================================
ERROR: test_g_function_match_sets (__main__.lab4a.test_g_function_match_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_sets()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 124, in test_g_function_match_sets
    self.assertTrue(lab4aStudent.match_sets(set1,set2) == set1&set2, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4a' has no attribute 'match_sets'

======================================================================
ERROR: test_h_function_diff_sets (__main__.lab4a.test_h_function_diff_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_sets()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 136, in test_h_function_diff_sets
    self.assertTrue(lab4aStudent.diff_sets(set1,set2) == set1^set2, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4a' has no attribute 'diff_sets'

======================================================================
ERROR: test_i_function_diff_sets (__main__.lab4a.test_i_function_diff_sets)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_sets()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 148, in test_i_function_diff_sets
    self.assertTrue(lab4aStudent.diff_sets(set1,set2) == set1^set2, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4a' has no attribute 'diff_sets'

======================================================================
ERROR: test_d_function_join_lists (__main__.lab4b.test_d_function_join_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_lists() joins lists together {1,2,3,4,5} and {2,1,0,-1,-2}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 206, in test_d_function_join_lists
    self.assertTrue(lab4bStudent.join_lists(list1,list2) == list(set(list1)|set(list2)), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4b' has no attribute 'join_lists'

======================================================================
ERROR: test_e_function_join_lists (__main__.lab4b.test_e_function_join_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function join_lists() joins lists together
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 218, in test_e_function_join_lists
    self.assertTrue(lab4bStudent.join_lists(list1,list2) == list(set(list1)|set(list2)), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4b' has no attribute 'join_lists'

======================================================================
ERROR: test_f_function_match_lists (__main__.lab4b.test_f_function_match_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_lists()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 230, in test_f_function_match_lists
    self.assertTrue(lab4bStudent.match_lists(list1,list2) == list(set(list1)&set(list2)), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4b' has no attribute 'match_lists'

======================================================================
ERROR: test_g_function_match_lists (__main__.lab4b.test_g_function_match_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function match_lists()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 242, in test_g_function_match_lists
    self.assertTrue(lab4bStudent.match_lists(list1,list2) == list(set(list1)&set(list2)), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4b' has no attribute 'match_lists'

======================================================================
ERROR: test_h_function_diff_lists (__main__.lab4b.test_h_function_diff_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_lists()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 254, in test_h_function_diff_lists
    self.assertTrue(lab4bStudent.diff_lists(list1,list2) == list(set(list1)^set(list2)), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4b' has no attribute 'diff_lists'

======================================================================
ERROR: test_i_function_diff_lists (__main__.lab4b.test_i_function_diff_lists)
[Lab 4] - [Investigation 1] - [Part 2] - Sets - function diff_lists()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 266, in test_i_function_diff_lists
    self.assertTrue(lab4bStudent.diff_lists(list1,list2) == list(set(list1)^set(list2)), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4b' has no attribute 'diff_lists'

======================================================================
ERROR: test_e_function_create_dictionary (__main__.lab4c.test_e_function_create_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function create_dictionary()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 325, in test_e_function_create_dictionary
    self.assertTrue(lab4cStudent.create_dictionary(list_keys,list_values) == dict_york, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4c' has no attribute 'create_dictionary'. Did you mean: 'invert_dictionary'?

======================================================================
ERROR: test_f_function_create_dictionary (__main__.lab4c.test_f_function_create_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function create_dictionary()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 338, in test_f_function_create_dictionary
    self.assertTrue(lab4cStudent.create_dictionary(list_keys,list_values) == dict_york, msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4c' has no attribute 'create_dictionary'. Did you mean: 'invert_dictionary'?

======================================================================
ERROR: test_i_function_split_dictionary (__main__.lab4c.test_i_function_split_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function shared_values()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 378, in test_i_function_split_dictionary
    self.assertTrue(lab4cStudent.shared_values(dict1, dict2) == set(dict1.values())&set(dict2.values()), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4c' has no attribute 'shared_values'

======================================================================
ERROR: test_j_function_split_dictionary (__main__.lab4c.test_j_function_split_dictionary)
[Lab 4] - [Investigation 1] - [Part 3] - Data Structures - function shared_values()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mint/ops445/lab4/./CheckLab4.py", line 390, in test_j_function_split_dictionary
    self.assertTrue(lab4cStudent.shared_values(dict1, dict2) == set(dict1.values())&set(dict2.values()), msg=error_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lab4c' has no attribute 'shared_values'

----------------------------------------------------------------------
Ran 51 tests in 0.124s

FAILED (errors=16)
